<a href="https://colab.research.google.com/github/SejalPawar13/MSC_FDS_504/blob/main/FDS_PRACTS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd


In [4]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])

<class 'numpy.ndarray'>
(3,)
1 2 3


In [5]:
b=np.array([[1,2],[3,4]])
b


array([[1, 2],
       [3, 4]])

In [6]:
print (b.shape)
print(b[0,0],b[0,1],b[1,1])

(2, 2)
1 2 4


In [7]:
c=np.array([[1,2],[3,4],[5,6]])
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
print(c[0,1],c[1,0],c[2,0],c[2,1])


2 3 5 6


In [9]:
d=np.zeros((2,3))
print(d)


[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
e=np.ones((4,2))
print(e)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:
f=np.full((2,2),9)
print(f)


[[9 9]
 [9 9]]


In [12]:
g=np.random.random((3,3))
print(g)


[[0.69925061 0.77616777 0.57137804]
 [0.57711834 0.77915593 0.37345997]
 [0.8973086  0.17556396 0.74455954]]


In [13]:
h=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(h)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
i=h[:2,1:3]
print(i)

[[2 3]
 [6 7]]
